{% set version = "0.13.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-udunits2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/udunits2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/udunits2/udunits2_{{ version }}.tar.gz
  sha256: 3e6dc4a12c155fa3e77f982084adbd6cb75d7a106d0b1a49ddc50a17fa4d045b
  patches:
    - patches/0001-minimal-ucrt-libs.patch

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - udunits2
    - expat  # [win]
  run:
    - r-base

test:
  commands:
    - $R -e "library('udunits2')"           # [not win]
    - "\"%R%\" -e \"library('udunits2')\""  # [win]

about:
  home: https://www.unidata.ucar.edu/software/udunits/
  dev_url: https://github.com/pacificclimate/Rudunits2
  license: GPL-2.0-only
  summary: Provides simple bindings to Unidata's udunits library.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
