appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: qwMYiWoGgcQkA/0+Kt+lCUv/+q8ZI4mUxHam2vTKLEd8g+Fxw96Ygcbu684xc/CrX7gxr19RmBU0ANCxUA63x0yqHid1wlk+3XLAx66yo5dTA2oGLQldp/S06simgvkTjrmZNVha1hlIgqdbgknzll7boncf4rJ9e5TXN8EzVSo//+t/QXx9/cXnIIIv2XkUZlcmbyu3DpDmymvAHYeQJskUsSxALYDPyIdDO3IFnQtLy4drNYDvo4uaPHewA1XYnGwQyish1NPmlqsMkYA5Ts1Howp810mga4ll+cddWoRKaYlI48vYkmHxfHAdQQhAq80eJzApgk25QBuYh/ayth1HW2flhEuXCUVQpnqur19C/2mEZiYeJP0dBPMJvIKe72lTw3h+SXZz05ouzkCEZe37zlzMyandrBIW8X+p+prf6vHhmfSbf61+OjW+/mhdrhnxaJz3GiW32jk1ArZ3tRx65mgTbvSW35zOB0jaiFbicy9t9tQDq13r7tijnrTR78dDaIh/lomCOaJf4UgA3kmCE26+3bVFFOlIANsB2YwIIzF939ifJ3Lop20t8xW9H16zYmgdgNuAySov/TBObyOH63XDKrjTWcZqhf6+ZeXzs78hhLuB5cMr0hH25hOhIlzYWpeElZ5NU9Wo+k20wt5MxqvGzzGTGIoCCEB+0/o=
